name: chicken-egg-counter
channels:
  - conda-forge
dependencies:
  - python=3.12  
  - numpy
  - pytorch
  - matplotlib
  - scikit-learn
  - onnx
  - onnxruntime
  - ultralytics=8.3.214
  - torchvision=0.20.1
  - opencv=4.10.0